name: nexcash_mvp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#19183B"           # warna background (gunakan hex)
  image: assets/logo.png     # gambar logo (pastikan sudah di folder assets)
  android: true
  ios: false
  web: false

flutter_launcher_icons:
  android: true
  ios: false        # ubah ke true kalau nanti build di Mac
  image_path: "assets/icon.png"   # path ke file icon kamu
  adaptive_icon_background: "#ffffff"  # warna background untuk Android 8+
  adaptive_icon_foreground: "assets/icon.png"



flutter:
  uses-material-design: true

  assets:
    - assets/
